name: nourishnet
description: "Food hunger management app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  cupertino_icons: ^1.0.2
  sign_in_button: ^3.2.0
  firebase_analytics: ^10.8.0
  get: ^4.6.6
  flutter_native_splash: ^2.3.10
  cloud_firestore: ^4.15.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  geocoding: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5
  get_storage: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    -   "assets/icon.png"
    - "assets/Donorp1.png"
    - "assets/Donorp2.png"
    - "assets/Donorp3.png"
    - "assets/DonorProfilePhoto.png"
    - "assets/posts1.png"
    - "assets/posts2.png"
    - "assets/posts3.png"
    - "assets/posts4.png"


  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
